#!/bin/bash

# Temporary file to store the result
TEMP_FILE="src/text-gen-models.ts.tmp"
OUTPUT_FILE="src/text-gen-models.ts"

# Get the JSON data
JSON_DATA=$(npx wrangler ai models --json | jq --arg date "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" '
  reduce .[] as $item (
    {last_update: $date, beta: [], ga: []};
    if ($item.task.name == "Text Generation") then
      if ($item.properties | any(.property_id == "beta" and .value == "true")) then
        .beta += [$item.name]
      else
        .ga += [$item.name]
      end
    else
      .
    end
  ) |
  .beta |= sort |
  .ga |= sort
')

# Check if the command succeeded
if [ $? -eq 0 ]; then
  # Extract data from JSON
  LAST_UPDATE=$(echo "$JSON_DATA" | jq -r '.last_update')
  BETA_MODELS=$(echo "$JSON_DATA" | jq -r '.beta[] | "    \"" + . + "\","' | sed '$ s/,$//')
  GA_MODELS=$(echo "$JSON_DATA" | jq -r '.ga[] | "    \"" + . + "\","' | sed '$ s/,$//')

  # Generate TypeScript file
  cat > "$TEMP_FILE" << EOF
/**
 * Cloudflare Workers AI Text Generation Models
 *
 * This file is auto-generated by get-text-gen-models.sh
 * DO NOT EDIT MANUALLY
 *
 * Last updated: ${LAST_UPDATE}
 */

export interface TextGenModels {
  /** 
   * ISO 8601 timestamp of when this data was last updated 
   * if user passing their own dont require last_update
   */
  last_update?: string;
  /** Beta/experimental text generation models */
  beta?: readonly string[];
  /** Generally available (GA) text generation models */
  ga?: readonly string[];
}

export const textGenModels: TextGenModels = {
  last_update: "${LAST_UPDATE}",
  beta: [
${BETA_MODELS}
  ] as const,
  ga: [
${GA_MODELS}
  ] as const
} as const;

EOF

  # Command succeeded, replace the output file
  mv "$TEMP_FILE" "$OUTPUT_FILE"
  echo "Successfully updated $OUTPUT_FILE"
else
  # Command failed, remove temp file and keep existing file
  rm -f "$TEMP_FILE"
  echo "Command failed. Existing $OUTPUT_FILE (if any) was preserved."
  exit 1
fi